import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import { ThemeProvider } from '@/components/theme-provider'
import WithPersistProvider from '@/components/providers/WithPersistProvider'
import { SocketProvider } from '@/components/providers/SocketProvider'
import WithLoadingProvider from '@/components/providers/WithLoadingProvider'

const roboto = Roboto({
  variable: '--roboto',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Levi E-Commerce',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning className='custom-scrollbar p-0'>
      <body className={roboto.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <WithPersistProvider>
            <SocketProvider>
              <WithLoadingProvider>{children}</WithLoadingProvider>
            </SocketProvider>
          </WithPersistProvider>
          <Toaster richColors={true} />
        </ThemeProvider>
      </body>
    </html>
  )
}
